### ISSUE TITLE
兄弟能支持ios与andriod的英文不？正好需要这个

### ISSUE THREAD

**Issue by shen2009fei** [lucasjinreal/vits_cpp#1]

**Comment by lucasjinreal** [comment]
理论可以，你只要能编译espeak即可，ort支持ios和android

**Comment by shen2009fei** [comment]
在macos Ventura 13.2 intel 平台 尝试编译失败。

/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/System/Library/Frameworks/AudioToolbox.framework/Headers/AudioComponent.h:516:39: error: expected ')' before '^' token
  516 |                                 void (^inCompletionHandler)(AudioComponentInstance __nullable, OSStatus))
      |                                       ^
      |                                       )
/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/System/Library/Frameworks/AudioToolbox.framework/Headers/AudioComponent.h:702:122: error: expected ')' before '^' token
  702 |                                                                   void                                                  (^inCompletionHandler)(AudioComponentValidationResult, CFDictionaryRef))
      |                                                                                                                          ^
      |                                                                                                                          )
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/System/Library/Frameworks/AudioToolbox.framework/Headers/AudioUnit.h:21,
                 from /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/System/Library/Frameworks/AudioToolbox.framework/Headers/AUGraph.h:30,
                 from /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/System/Library/Frameworks/AudioToolbox.framework/Headers/AudioToolbox.h:21:
/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/System/Library/Frameworks/AudioToolbox.framework/Headers/AudioUnitProperties.h:1386:15: error: expected identifier or '(' before '^' token
 1386 | typedef void (^AURenderContextObserver)(const AudioUnitRenderContext *context)
      |               ^
/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/System/Library/Frameworks/AudioToolbox.framework/Headers/AudioUnitProperties.h:1413:19: error: expected identifier or '(' before '^' token
 1413 | typedef OSStatus (^ AUMIDIEventListBlock)(AUEventSampleTime                                     eventSampleTime,
      |                   ^
/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/System/Library/Frameworks/AudioToolbox.framework/Headers/AudioUnitProperties.h:1753:15: error: expected identifier or '(' before '^' token
 1753 | typedef void (^AudioUnitRemoteControlEventListener)(AudioUnitRemoteControlEvent event);
      |               ^
/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/System/Library/Frameworks/AudioToolbox.framework/Headers/AudioUnitProperties.h:2625:15: error: expected identifier or '(' before '^' token
 2625 | typedef void (^AUVoiceIOMutedSpeechActivityEventListener)(AUVoiceIOSpeechActivityEvent event);
      |               ^
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/System/Library/Frameworks/AudioToolbox.framework/Headers/AudioServices.h:21,
                 from /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/System/Library/Frameworks/AudioToolbox.framework/Headers/AudioToolbox.h:30:
/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/System/Library/Frameworks/CoreAudio.framework/Headers/AudioHardware.h:162:2: error: expected identifier or '(' before '^' token
  162 | (^AudioObjectPropertyListenerBlock)(    UInt32                              inNumberAddresses,
      |  ^
/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/System/Library/Frameworks/CoreAudio.framework/Headers/AudioHardware.h:400:41: error: unknown type name 'AudioObjectPropertyListenerBlock'; did you mean 'AudioObjectPropertyListenerProc'?
  400 |                                         AudioObjectPropertyListenerBlock    inListener)             __OSX_AVAILABLE_STARTING(__MAC_10_7, __IPHONE_7_0);
      |                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                         AudioObjectPropertyListenerProc
/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/System/Library/Frameworks/CoreAudio.framework/Headers/AudioHardware.h:421:41: error: unknown type name 'AudioObjectPropertyListenerBlock'; did you mean 'AudioObjectPropertyListenerProc'?
  421 |                                         AudioObjectPropertyListenerBlock    inListener)             __OSX_AVAILABLE_STARTING(__MAC_10_7, __IPHONE_7_0);
      |                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                         AudioObjectPropertyListenerProc
/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/System/Library/Frameworks/CoreAudio.framework/Headers/AudioHardware.h:804:2: error: expected identifier or '(' before '^' token
  804 | (^AudioDeviceIOBlock)(  const AudioTimeStamp*   inNow,
      |  ^
/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/System/Library/Frameworks/CoreAudio.framework/Headers/AudioHardware.h:1353:37: error: unknown type name 'AudioDeviceIOBlock'; did you mean 'AudioDeviceIOProc'?
 1353 |                                     AudioDeviceIOBlock                          inIOBlock)                              __OSX_AVAILABLE_STARTING(__MAC_10_7, __IPHONE_7_0);
      |                                     ^~~~~~~~~~~~~~~~~~
      |                                     AudioDeviceIOProc
/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/System/Library/Frameworks/AudioToolbox.framework/Headers/AudioServices.h:212:51: error: expected ')' before '^' token
  212 |                                             void (^__nullable inCompletionBlock)(void))
      |                                                   ^
      |                                                   )
/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/System/Library/Frameworks/AudioToolbox.framework/Headers/AudioServices.h:229:55: error: expected ')' before '^' token
  229 |                                                 void (^__nullable inCompletionBlock)(void))
      |                                                       ^
      |                                                       )
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/System/Library/Frameworks/AudioToolbox.framework/Headers/MusicPlayer.h:44,
                 from /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/System/Library/Frameworks/AudioToolbox.framework/Headers/AudioToolbox.h:39:
/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/System/Library/Frameworks/CoreMIDI.framework/Headers/MIDIServices.h:322:2: error: expected identifier or '(' before '^' token
  322 | (^MIDINotifyBlock)(const MIDINotification *message);
      |  ^
/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/System/Library/Frameworks/CoreMIDI.framework/Headers/MIDIServices.h:342:2: error: expected identifier or '(' before '^' token
  342 | (^MIDIReceiveBlock)(const MIDIEventList *evtlist, void * __nullable srcConnRefCon);
      |  ^
/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/System/Library/Frameworks/CoreMIDI.framework/Headers/MIDIServices.h:385:2: error: expected identifier or '(' before '^' token
  385 | (^MIDIReadBlock)(const MIDIPacketList *pktlist, void * __nullable srcConnRefCon) API_DEPRECATED("use MIDIReceiveBlock and MIDIEventLists", macos(10.11, API_TO_BE_DEPRECATED), ios(9.0, API_TO_BE_DEPRECATED)) __TVOS_PROHIBITED __WATCHOS_PROHIBITED;
      |  ^
/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/System/Library/Frameworks/CoreMIDI.framework/Headers/MIDIServices.h:1303:41: error: unknown type name 'MIDINotifyBlock'; did you mean 'MIDINotifyProc'?
 1303 |                                         MIDINotifyBlock __nullable      notifyBlock )                   API_AVAILABLE(macos(10.11), ios(9.0)) API_UNAVAILABLE(tvos, watchos);
      |                                         ^~~~~~~~~~~~~~~
      |                                         MIDINotifyProc
/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/System/Library/Frameworks/CoreMIDI.framework/Headers/MIDIServices.h:1361:65: error: unknown type name 'MIDIReceiveBlock'
 1361 |                                                                 MIDIReceiveBlock receiveBlock ) API_AVAILABLE(macos(11.0), ios(14.0)) API_UNAVAILABLE(tvos, watchos);
      |                                                                 ^~~~~~~~~~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/System/Library/Frameworks/CoreMIDI.framework/Headers/MIDIServices.h:1426:65: error: unknown type name 'MIDIReadBlock'; did you mean 'MIDIReadProc'?
 1426 |                                                                 MIDIReadBlock   readBlock )
      |                                                                 ^~~~~~~~~~~~~
      |                                                                 MIDIReadProc
/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/System/Library/Frameworks/CoreMIDI.framework/Headers/MIDIServices.h:1780:73: error: unknown type name 'MIDIReceiveBlock'
 1780 |                                                                         MIDIReceiveBlock        readBlock ) API_AVAILABLE(macos(11.0), ios(14.0)) API_UNAVAILABLE(tvos, watchos);
      |                                                                         ^~~~~~~~~~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/System/Library/Frameworks/CoreMIDI.framework/Headers/MIDIServices.h:1861:65: error: unknown type name 'MIDIReadBlock'; did you mean 'MIDIReadProc'?
 1861 |                                                                 MIDIReadBlock           readBlock )
      |                                                                 ^~~~~~~~~~~~~
      |                                                                 MIDIReadProc
make: *** [src/libpcaudio_la-coreaudio.lo] Error 1

**Comment by lucasjinreal** [comment]
可以需要先编译epeck-ng ，我项目里面只是把windows的dll丢进去了， 你需要自己替换为.a
